// <auto-generated />
namespace Wed_Do_An.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cre));
        
        string IMigrationMetadata.Id
        {
            get { return "202303230720480_cre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
